# Gans data pipeline: Phase 2, Google Cloud SQL

Same pipeline as the local notebook, but the data now lands in a **MySQL instance on Google Cloud SQL**. Anyone in the company can query it, and a Cloud Function can update it automatically.

| Step | Source | Method | Table(s) filled |
|---|---|---|---|
| 1 | Wikipedia | Web scraping (BeautifulSoup) | `cities`, `population` |
| 2 | OpenWeather 5-day forecast | REST API | `weather` |
| 3 | AeroDataBox (RapidAPI) | REST API | `airports`, `city_airports` |
| 4 | AeroDataBox (RapidAPI) | REST API | `flights` (tomorrow's arrivals) |

**Why run it from a notebook first?** Steps 1 and 3 fill *static* tables (cities and airports rarely change), so running them once by hand is enough. Steps 2 and 4 change every day. Those are the parts that later move into the Cloud Function. Proving them here first means the cloud deployment only has to deal with cloud problems, not code problems.

**Before running:** connect MySQL Workbench to the Cloud SQL instance and execute `sql/02_create_database_cloud.sql`.

## 1. Set-up: libraries, secrets and settings

**What:** imports every library once at the top, loads the API keys and password from a `.env` file, and defines the cities we track.
**Why:** one import cell makes the notebook's dependencies obvious. Secrets in `.env` (which `.gitignore` excludes) mean the code can go to GitHub without leaking keys.

In [1]:
# --- Standard library ---
import os                                  # read secrets from environment variables
from datetime import datetime, timedelta   # build "now" and "tomorrow" for the flight query
from zoneinfo import ZoneInfo              # timezone-aware timestamps (Gans operates on Berlin time)

# --- Third-party ---
import requests                            # HTTP calls to Wikipedia, OpenWeather and AeroDataBox
import pandas as pd                        # every source is shaped into a DataFrame before loading
from bs4 import BeautifulSoup              # parse Wikipedia's HTML and find the infobox values
from lat_lon_parser import parse           # turn 52°31′12″N-style coordinates into decimal degrees
from dotenv import load_dotenv             # read the .env file with the password and API keys
from sqlalchemy import create_engine, text, URL  # engine = connection to MySQL; text() = parameterised SQL

In [2]:
# .env lives OUTSIDE the repository so secrets can never be committed by accident
load_dotenv()

MYSQL_PASSWORD = os.getenv("password")
OPENWEATHER_API_KEY = os.getenv("openWeatherApi")
AERODATABOX_API_KEY = os.getenv("AeroDATAboxAPI")
CLOUD_SQL_HOST = os.getenv("cloud_sql_host")  # public IP of the Cloud SQL instance, kept in .env, not in the code

# Fail early with a clear message, instead of a confusing error deep inside an API call
required = {
    "password": MYSQL_PASSWORD,
    "openWeatherApi": OPENWEATHER_API_KEY,
    "AeroDATAboxAPI": AERODATABOX_API_KEY,
    "cloud_sql_host": CLOUD_SQL_HOST,
}
missing = [name for name, value in required.items() if not value]
if missing:
    raise ValueError(f"Missing in your .env file: {missing}")
print("All secrets loaded (values hidden).")

CITIES = ["Berlin", "Hamburg", "Munich"]   # the three German cities Gans launches in
BERLIN_TZ = ZoneInfo("Europe/Berlin")      # one timezone for every timestamp we create

All secrets loaded (values hidden).

## 2. Connect Python to Google Cloud SQL

**What:** builds a SQLAlchemy `engine` pointing at the public IP of the Cloud SQL instance.
**Why `URL.create` instead of an f-string?** My Cloud SQL password contains special characters. In a plain `mysql+pymysql://user:password@host` string they get mistaken for URL syntax. `URL.create` escapes them safely.
**Why is the IP in `.env`?** The instance accepts connections from any address (`0.0.0.0/0`, as the course set-up suggests). Publishing the IP on GitHub next to the code would make it an easy target.

In [3]:
SCHEMA = "sql_cities_weather_flights"  # must match the database created by the SQL script

connection_url = URL.create(
    drivername="mysql+pymysql",   # PyMySQL is the pure-Python driver SQLAlchemy uses to talk to MySQL
    username="root",
    password=MYSQL_PASSWORD,      # the Cloud SQL instance password, not the local one
    host=CLOUD_SQL_HOST,          # public IP from the Cloud SQL overview page
    port=3306,
    database=SCHEMA,
)
engine = create_engine(connection_url)

# Sanity check: proves the laptop can reach the cloud instance before we send any data
with engine.connect() as connection:
    print("Connected to:", connection.execute(text("SELECT DATABASE()")).scalar())

Connected to: sql_cities_weather_flights

## 3. Cities and population: web scraping Wikipedia

**What:** downloads each city's Wikipedia page once and reads the infobox for **country, latitude, longitude and population**.
**Why Wikipedia?** The community keeps it up to date, unlike a static CSV that silently goes stale. Every city page uses the same infobox layout, so one loop works for all three cities.
**Why two tables?** A city's location never changes, but its population does. `cities` holds the fixed facts. `population` keeps one row per city *per date*, so history builds up instead of being overwritten.

In [4]:
def get_wikipedia_soup(city):
    """Download a city's English Wikipedia page and return it as parsed HTML."""
    url = f"https://en.wikipedia.org/wiki/{city}"
    headers = {"User-Agent": "Chrome/134.0.0.0"}   # Wikipedia rejects requests that carry no browser-like user agent
    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()                    # stop on 404/500 instead of parsing an error page
    return BeautifulSoup(response.content, "html.parser")


def scrape_cities(cities):
    """Return two DataFrames: static city facts and a dated population snapshot."""
    city_rows, population_rows = [], []
    today = datetime.now(BERLIN_TZ).date()         # population is stamped with the day it was collected

    for city in cities:
        soup = get_wikipedia_soup(city)            # one request per city, reused for every field

        city_rows.append({
            "city": city,
            # first infobox value is the country; strip() removes the leading space Wikipedia leaves in
            "country": soup.find(class_="infobox-data").get_text(strip=True),
            "latitude": parse(soup.find(class_="latitude").get_text()),
            "longitude": parse(soup.find(class_="longitude").get_text()),
        })

        # the number sits in the table cell right after the "Population" label, e.g. "3,597,000"
        population_text = soup.find(string="Population").find_next("td").get_text(strip=True)
        population_rows.append({
            "city": city,
            "population": int(population_text.replace(",", "")),   # "3,597,000" -> 3597000
            "timestamp_population": today,
        })

    return pd.DataFrame(city_rows), pd.DataFrame(population_rows)

In [5]:
def save_cities_and_population(cities_df, population_df):
    """Upsert cities, then insert today's population using each city's database id."""
    with engine.begin() as connection:             # begin() = one transaction, committed automatically at the end
        for row in cities_df.to_dict("records"):
            # UNIQUE(city) makes re-runs update the existing row instead of creating a duplicate city
            connection.execute(text("""
                INSERT INTO cities (city, country, latitude, longitude)
                VALUES (:city, :country, :latitude, :longitude)
                ON DUPLICATE KEY UPDATE
                    country = VALUES(country),
                    latitude = VALUES(latitude),
                    longitude = VALUES(longitude)
            """), row)

        for row in population_df.to_dict("records"):
            # population is linked by city_id (the foreign key), so look the id up first
            city_id = connection.execute(
                text("SELECT city_id FROM cities WHERE city = :city"), {"city": row["city"]}
            ).scalar()
            if city_id is None:
                print(f"City '{row['city']}' not found in cities table, skipped.")
                continue

            # primary key (city_id, timestamp_population): a second run on the same day just refreshes the value
            connection.execute(text("""
                INSERT INTO population (city_id, population, timestamp_population)
                VALUES (:city_id, :population, :timestamp_population)
                ON DUPLICATE KEY UPDATE population = VALUES(population)
            """), {"city_id": city_id, "population": row["population"],
                   "timestamp_population": row["timestamp_population"]})


cities_scraped_df, population_df = scrape_cities(CITIES)
save_cities_and_population(cities_scraped_df, population_df)

# Read the cities back WITH their database ids: every later step joins on city_id
cities_df = pd.read_sql("SELECT city_id, city, country, latitude, longitude FROM cities", con=engine)
cities_df

   city_id     city  country  latitude  longitude
0        1   Berlin  Germany   52.5200     13.405
1        2  Hamburg  Germany   53.5500     10.000
2        3   Munich  Germany   48.1375     11.575

## 4. Weather forecast: OpenWeather API

**What:** for every city in the `cities` table, calls OpenWeather's **5-day / 3-hour forecast** and keeps temperature, the main condition (Clear, Clouds, Rain…), rain volume and wind speed. That gives 40 forecast slots per city.
**Why these fields?** Scooter use drops sharply in rain, cold and strong wind. Those are exactly the signals a rebalancing model needs.
**Why read coordinates from SQL instead of the city name?** Coordinates avoid ambiguity (there is more than one "Hamburg" in the world), and the database stays the single source of truth.
**Why `append`?** Every run is a new snapshot, identified by `data_retrieved_at`. Keeping old snapshots lets us later measure how accurate the forecasts were.

In [6]:
def get_weather_forecast(cities_df, api_key):
    """Return a DataFrame with the 5-day / 3-hour forecast for every city in cities_df."""
    weather_rows = []
    retrieved_at = datetime.now(BERLIN_TZ).replace(tzinfo=None)   # MySQL DATETIME has no timezone, so store Berlin time

    for city in cities_df.to_dict("records"):
        url = "https://api.openweathermap.org/data/2.5/forecast"
        params = {"lat": city["latitude"], "lon": city["longitude"],
                  "appid": api_key, "units": "metric"}             # metric -> °C and m/s
        response = requests.get(url, params=params, timeout=30)
        response.raise_for_status()                                # a bad key or quota error stops here, loudly

        for slot in response.json()["list"]:                       # one entry per 3-hour slot
            weather_rows.append({
                "city_id": city["city_id"],
                "city": city["city"],
                "forecast_time": slot["dt_txt"],                   # e.g. "2026-10-02 09:00:00" (UTC)
                "temperature": slot["main"].get("temp"),
                "forecast": slot["weather"][0].get("main"),        # Clear / Clouds / Rain ...
                "rain_in_last_3h": slot.get("rain", {}).get("3h", 0),   # key is absent when it doesn't rain -> 0
                "wind_speed": slot["wind"].get("speed"),
                "data_retrieved_at": retrieved_at,
            })

    if not weather_rows:                                           # no cities in the table -> nothing to store
        return pd.DataFrame(weather_rows)
    weather_df = pd.DataFrame(weather_rows)
    weather_df["forecast_time"] = pd.to_datetime(weather_df["forecast_time"])   # text -> real datetime for MySQL
    return weather_df


weather_df = get_weather_forecast(cities_df, OPENWEATHER_API_KEY)

# weather_entry_id is AUTO_INCREMENT in MySQL, so pandas only sends the data columns
weather_df.to_sql("weather", con=engine, if_exists="append", index=False)
weather_df.head()

,city_id,city,forecast_time,temperature,forecast,rain_in_last_3h,wind_speed,data_retrieved_at
0,1,Berlin,2026-10-02 15:00:00,17.16,Clouds,0.0,2.24,2026-10-02 15:00:11.166941
1,1,Berlin,2026-10-02 18:00:00,14.93,Clouds,0.0,0.91,2026-10-02 15:00:11.166941
2,1,Berlin,2026-10-02 21:00:00,10.37,Clouds,0.0,0.17,2026-10-02 15:00:11.166941
3,1,Berlin,2026-10-03 00:00:00,13.64,Clouds,0.0,0.67,2026-10-02 15:00:11.166941
4,1,Berlin,2026-10-03 03:00:00,12.76,Clouds,0.0,0.77,2026-10-02 15:00:11.166941

## 5. Airports near each city: AeroDataBox API

**What:** asks AeroDataBox for airports within 50 km of each city's coordinates, keeping only airports that have flight data.
**Why?** Gans wants tourists, and tourists arrive by plane. Before we can count arrivals we need to know *which* airports serve each city. Berlin has two in the API (BER and the closed Tegel). Hamburg and Munich have one each.
**Why two tables?** `airports` stores each airport once. `city_airports` is the link table, because one city can have several airports.

In [7]:
AERODATABOX_HEADERS = {
    "X-RapidAPI-Key": AERODATABOX_API_KEY,          # RapidAPI authenticates with these two headers
    "X-RapidAPI-Host": "aerodatabox.p.rapidapi.com",
}


def find_airports_near_cities(cities_df, radius_km=50):
    """Return (airports_df, city_airports_df) for airports near each city."""
    airport_rows, link_rows = [], []

    for city in cities_df.to_dict("records"):
        response = requests.get(
            "https://aerodatabox.p.rapidapi.com/airports/search/location",
            headers=AERODATABOX_HEADERS,
            params={"lat": city["latitude"], "lon": city["longitude"],
                    "radiusKm": radius_km, "limit": 10,
                    "withFlightInfoOnly": "true"},   # skip airfields with no schedule data
            timeout=30,
        )
        if response.status_code != 200:
            print(f"Airport search failed for {city['city']}: {response.status_code}")
            continue

        for airport in response.json().get("items", []):
            if not airport.get("icao"):              # ICAO code is our primary key, so it can't be missing
                continue
            airport_rows.append({"airport_icao": airport["icao"], "airport_name": airport.get("name")})
            link_rows.append({"city_id": int(city["city_id"]), "city": city["city"],
                              "airport_icao": airport["icao"]})

    # explicit columns keep the code working even if every API call failed and the lists are empty
    airports_df = (pd.DataFrame(airport_rows, columns=["airport_icao", "airport_name"])
                   .drop_duplicates(subset=["airport_icao"]))
    city_airports_df = (pd.DataFrame(link_rows, columns=["city_id", "city", "airport_icao"])
                        .drop_duplicates(subset=["city_id", "airport_icao"]))
    return airports_df, city_airports_df


airports_df, city_airports_df = find_airports_near_cities(cities_df)
city_airports_df

   city_id     city airport_icao
0        1   Berlin         EDDT
1        1   Berlin         EDDB
2        2  Hamburg         EDDH
3        3   Munich         EDDM

## 6. Tomorrow's arrivals: AeroDataBox flight schedules

**What:** for every airport, downloads the arrivals scheduled for **tomorrow** and keeps flight number, scheduled arrival time and departure airport.
**Why tomorrow?** The operations team rebalances scooters ahead of demand. Knowing tonight how many planes land tomorrow, and when, is what makes that possible.
**Why two 12-hour calls per airport?** The schedule endpoint accepts at most a 12-hour window, so a full day is 00:00–11:59 plus 12:00–23:59.
**Why the filters?** Cancelled flights, cargo, private jets and codeshare copies (one plane sold under several flight numbers) would all inflate the passenger count.

In [8]:
def tomorrows_flight_arrivals(icao_list):
    """Return a DataFrame with tomorrow's scheduled passenger arrivals for each airport."""
    tomorrow = datetime.now(BERLIN_TZ).date() + timedelta(days=1)   # "tomorrow" in Berlin, not in UTC
    half_days = [("00:00", "11:59"), ("12:00", "23:59")]           # API limit: max 12 hours per request
    retrieved_at = datetime.now(BERLIN_TZ).replace(tzinfo=None)
    arrival_rows = []

    for icao in icao_list:
        for start, end in half_days:
            url = (f"https://aerodatabox.p.rapidapi.com/flights/airports/icao/"
                   f"{icao}/{tomorrow}T{start}/{tomorrow}T{end}")
            params = {
                "direction": "Arrival",      # only flights landing at this airport
                "withLeg": "true",           # include the departure airport of each flight
                "withCancelled": "false",
                "withCodeshared": "false",   # one physical plane = one row
                "withCargo": "false",
                "withPrivate": "false",
                "withLocation": "false",     # live aircraft position is not needed
            }
            response = requests.get(url, headers=AERODATABOX_HEADERS, params=params, timeout=30)

            # 204 = "no content": e.g. Berlin-Tegel (EDDT), closed since 2020, has no flights any more
            if response.status_code != 200:
                print(f"{icao} {start}-{end}: no data (HTTP {response.status_code})")
                continue

            arrivals = response.json().get("arrivals") or []
            print(f"{icao} | {tomorrow} {start}-{end} | {len(arrivals)} arrivals")

            for flight in arrivals:
                departure_airport = (flight.get("departure") or {}).get("airport") or {}
                scheduled = ((flight.get("arrival") or {}).get("scheduledTime") or {}).get("local")

                # a flight without number, time or origin can't be stored (all are NOT NULL in MySQL)
                if not (flight.get("number") and scheduled and departure_airport.get("icao")):
                    continue

                arrival_rows.append({
                    "flight_number": flight["number"],
                    "airline": (flight.get("airline") or {}).get("name"),
                    "arrival_airport_icao": icao,
                    # scheduled (not revised) time: stable, comparable from one day to the next
                    "arrival_time": scheduled,
                    "arrival_terminal": (flight.get("arrival") or {}).get("terminal"),
                    "departure_airport_icao": departure_airport["icao"],
                    "departure_airport_name": departure_airport.get("name"),
                    "departure_city": departure_airport.get("municipalityName"),
                    "data_retrieved_at": retrieved_at,
                })

    arrivals_df = pd.DataFrame(arrival_rows)
    if arrivals_df.empty:
        return arrivals_df

    # "2026-10-02 06:15+02:00" -> 2026-10-02 06:15 (local time, no offset: MySQL DATETIME can't store one)
    arrivals_df["arrival_time"] = (pd.to_datetime(arrivals_df["arrival_time"].str[:16], errors="coerce"))
    arrivals_df = arrivals_df.dropna(subset=["arrival_time"])

    # safety net: keep only tomorrow, remove repeats, sort chronologically
    arrivals_df = (arrivals_df[arrivals_df["arrival_time"].dt.date == tomorrow]
                   .drop_duplicates(subset=["flight_number", "departure_airport_icao",
                                            "arrival_airport_icao", "arrival_time"])
                   .sort_values("arrival_time")
                   .reset_index(drop=True))
    return arrivals_df


icao_codes = city_airports_df["airport_icao"].unique().tolist()
arrivals_df = tomorrows_flight_arrivals(icao_codes)
print("Arriving flights tomorrow:", len(arrivals_df))
arrivals_df.head()

EDDT 00:00-11:59: no data (HTTP 204)
EDDT 12:00-23:59: no data (HTTP 204)
EDDB | 2026-10-03 00:00-11:59 | 82 arrivals
EDDB | 2026-10-03 12:00-23:59 | 155 arrivals
EDDH | 2026-10-03 00:00-11:59 | 47 arrivals
EDDH | 2026-10-03 12:00-23:59 | 108 arrivals
EDDM | 2026-10-03 00:00-11:59 | 184 arrivals
EDDM | 2026-10-03 12:00-23:59 | 276 arrivals
Arriving flights tomorrow: 852

,flight_number,airline,arrival_airport_icao,arrival_time,arrival_terminal,departure_airport_icao,departure_airport_name,departure_city,data_retrieved_at
0,KU 171,Kuwait,EDDM,2026-10-03 01:40:00,NaN,EDDF,Frankfurt-am-Main,None,2026-10-02 15:00:24.099844
1,LH 773,Lufthansa,EDDM,2026-10-03 05:15:00,2,VTBS,Bangkok,None,2026-10-02 15:00:24.099844
2,LH 769,Lufthansa,EDDM,2026-10-03 05:15:00,2,WSSS,Singapore,None,2026-10-02 15:00:24.099844
3,LH 1743,Lufthansa,EDDM,2026-10-03 05:30:00,2,LTFM,Istanbul,None,2026-10-02 15:00:24.099844
4,XQ 966,Sun Express,EDDB,2026-10-03 06:05:00,1,LTBJ,İzmir,None,2026-10-02 15:00:24.099844

## 7. Save airports, city–airport links and flights

**What:** writes the three flight-related tables in the order the foreign keys require: **airports → city_airports → flights**.
**Why add the departure airports too?** `flights.departure_icao` is a foreign key to `airports`. A flight from Singapore can only be stored once Singapore's airport exists in `airports`, and the flight response already contains its name, so no extra API call is needed.
**Why `INSERT IGNORE` / `ON DUPLICATE KEY UPDATE`?** The pipeline runs every day. Re-running it must not crash on, or duplicate, rows that are already there. The `uq_flight` unique key in MySQL is the final guard.

In [9]:
# Airports seen as flight origins, named by their real airport name (fallback: city name)
route_airports_df = (
    arrivals_df.assign(airport_name=arrivals_df["departure_airport_name"].fillna(arrivals_df["departure_city"]))
    .rename(columns={"departure_airport_icao": "airport_icao"})[["airport_icao", "airport_name"]]
    if not arrivals_df.empty else pd.DataFrame(columns=["airport_icao", "airport_name"])
)
all_airports_df = (pd.concat([airports_df, route_airports_df], ignore_index=True)
                   .dropna(subset=["airport_name"])                           # airport_name is NOT NULL: drop blanks first...
                   .drop_duplicates(subset=["airport_icao"], keep="first"))   # ...then dedupe, nearby-airport names win
print("Unique airports to store:", len(all_airports_df))

with engine.begin() as connection:
    # 1) airports: parent table, must exist before anything points to it
    for row in all_airports_df.to_dict("records"):
        connection.execute(text("""
            INSERT INTO airports (airport_icao, airport_name)
            VALUES (:airport_icao, :airport_name)
            ON DUPLICATE KEY UPDATE airport_name = VALUES(airport_name)
        """), row)

    # 2) city_airports: which airport serves which city
    for row in city_airports_df.to_dict("records"):
        connection.execute(text("""
            INSERT IGNORE INTO city_airports (city_id, city, airport_icao)
            VALUES (:city_id, :city, :airport_icao)
        """), {"city_id": int(row["city_id"]), "city": row["city"], "airport_icao": row["airport_icao"]})

    # 3) flights: tomorrow's arrivals; the uq_flight key silently skips rows already stored
    for row in arrivals_df.to_dict("records"):
        connection.execute(text("""
            INSERT IGNORE INTO flights (flight_num, departure_icao, arrival_icao, arrival_time)
            VALUES (:flight_num, :departure_icao, :arrival_icao, :arrival_time)
        """), {"flight_num": row["flight_number"], "departure_icao": row["departure_airport_icao"],
               "arrival_icao": row["arrival_airport_icao"], "arrival_time": row["arrival_time"]})

print("Airports, city_airports and flights saved.")

Unique airports to store: 200
Airports, city_airports and flights saved.

## 8. Check what landed in the database

**What:** counts the rows in every table and shows a sample of the newest flights.
**Why:** a pipeline that "ran without errors" is not the same as one that stored the right data. This is the quickest proof.

In [10]:
tables = ["cities", "population", "weather", "airports", "city_airports", "flights"]
with engine.connect() as connection:
    for table in tables:
        count = connection.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar()   # table names come from our own list, not user input
        print(f"{table:<15}{count:>8} rows")

pd.read_sql("""
    SELECT f.flight_num, f.departure_icao, a.airport_name AS departure_airport,
           f.arrival_icao, ca.city AS arrival_city, f.arrival_time
    FROM flights f
    JOIN airports a        ON a.airport_icao = f.departure_icao
    JOIN city_airports ca  ON ca.airport_icao = f.arrival_icao
    ORDER BY f.arrival_time
    LIMIT 10
""", con=engine)

cities                3 rows
population            3 rows
weather             120 rows
airports            200 rows
city_airports         4 rows
flights             852 rows

,flight_num,departure_icao,departure_airport,arrival_icao,arrival_city,arrival_time
0,KU 171,EDDF,Frankfurt-am-Main,EDDM,Munich,2026-10-03 01:40:00
1,LH 773,VTBS,Bangkok,EDDM,Munich,2026-10-03 05:15:00
2,LH 769,WSSS,Singapore,EDDM,Munich,2026-10-03 05:15:00
3,LH 1743,LTFM,Istanbul,EDDM,Munich,2026-10-03 05:30:00
4,XQ 966,LTBJ,İzmir,EDDB,Berlin,2026-10-03 06:05:00
5,XQ 986,LTBJ,İzmir,EDDM,Munich,2026-10-03 06:05:00
6,SZ 121,UTDD,Dushanbe,EDDM,Munich,2026-10-03 06:05:00
7,LH 727,ZSPD,Shanghai,EDDM,Munich,2026-10-03 06:20:00
8,VN 35,VVNB,Hanoi,EDDM,Munich,2026-10-03 06:20:00
9,VL 1661,LRTR,Timişoara,EDDM,Munich,2026-10-03 06:30:00

## Done. Next step: automation

The notebook proves every step works against Cloud SQL. The daily-changing parts (weather and tomorrow's flights) are packaged in `cloud_function/main.py`, deployed as a Google Cloud Run function, and triggered once a day by Cloud Scheduler. After that, nobody has to open this notebook for the data to keep flowing.